<?php

    namespace Database\Seeders\Master;

    use App\Models\Master\City;
    use App\Models\Master\Province;
    use Illuminate\Database\Console\Seeds\WithoutModelEvents;
    use Illuminate\Database\Seeder;

    class CitiesSeeder extends Seeder
    {
        /**
         * Run the database seeds.
         *
         * @return void
         */
        public function run()
        {
            $data = $this->data();

            foreach ($data as $value) {
                City::create([
                    'country_id' => 1,
                    'province_id' => $this->getProvinceId($value['province_id']),
                    'area_code'   => $value['area_code'],
                    'name' => $value['name'],
                ]);
            }
        }

        function getProvinceId($areacode)
        {
            $province = Province::where('area_code', $areacode)->first();

            return $province->id;
        }

        public function data()
        {
            return [
                ['province_id' => 11, 'area_code' => '11.01', 'name' => 'KAB. ACEH SELATAN'],
                ['province_id' => 11, 'area_code' => '11.02', 'name' => 'KAB. ACEH TENGGARA'],
                ['province_id' => 11, 'area_code' => '11.03', 'name' => 'KAB. ACEH TIMUR'],
                ['province_id' => 11, 'area_code' => '11.04', 'name' => 'KAB. ACEH TENGAH'],
                ['province_id' => 11, 'area_code' => '11.05', 'name' => 'KAB. ACEH BARAT'],
                ['province_id' => 11, 'area_code' => '11.06', 'name' => 'KAB. ACEH BESAR'],
                ['province_id' => 11, 'area_code' => '11.07', 'name' => 'KAB. PIDIE'],
                ['province_id' => 11, 'area_code' => '11.08', 'name' => 'KAB. ACEH UTARA'],
                ['province_id' => 11, 'area_code' => '11.09', 'name' => 'KAB. SIMEULUE'],
                ['province_id' => 11, 'area_code' => '11.10', 'name' => 'KAB. ACEH SINGKIL'],
                ['province_id' => 11, 'area_code' => '11.11', 'name' => 'KAB. BIREUEN'],
                ['province_id' => 11, 'area_code' => '11.12', 'name' => 'KAB. ACEH BARAT DAYA'],
                ['province_id' => 11, 'area_code' => '11.13', 'name' => 'KAB. GAYO LUES'],
                ['province_id' => 11, 'area_code' => '11.14', 'name' => 'KAB. ACEH JAYA'],
                ['province_id' => 11, 'area_code' => '11.15', 'name' => 'KAB. NAGAN RAYA'],
                ['province_id' => 11, 'area_code' => '11.16', 'name' => 'KAB. ACEH TAMIANG'],
                ['province_id' => 11, 'area_code' => '11.17', 'name' => 'KAB. BENER MERIAH'],
                ['province_id' => 11, 'area_code' => '11.18', 'name' => 'KAB. PIDIE JAYA'],
                ['province_id' => 11, 'area_code' => '11.71', 'name' => 'KOTA BANDA ACEH'],
                ['province_id' => 11, 'area_code' => '11.72', 'name' => 'KOTA SABANG'],
                ['province_id' => 11, 'area_code' => '11.73', 'name' => 'KOTA LHOKSEUMAWE'],
                ['province_id' => 11, 'area_code' => '11.74', 'name' => 'KOTA LANGSA'],
                ['province_id' => 11, 'area_code' => '11.75', 'name' => 'KOTA SUBULUSSALAM'],
                ['province_id' => 12, 'area_code' => '12.01', 'name' => 'KAB. TAPANULI TENGAH'],
                ['province_id' => 12, 'area_code' => '12.02', 'name' => 'KAB. TAPANULI UTARA'],
                ['province_id' => 12, 'area_code' => '12.03', 'name' => 'KAB. TAPANULI SELATAN'],
                ['province_id' => 12, 'area_code' => '12.04', 'name' => 'KAB. NIAS'],
                ['province_id' => 12, 'area_code' => '12.05', 'name' => 'KAB. LANGKAT'],
                ['province_id' => 12, 'area_code' => '12.06', 'name' => 'KAB. KARO'],
                ['province_id' => 12, 'area_code' => '12.07', 'name' => 'KAB. DELI SERDANG'],
                ['province_id' => 12, 'area_code' => '12.08', 'name' => 'KAB. SIMALUNGUN'],
                ['province_id' => 12, 'area_code' => '12.09', 'name' => 'KAB. ASAHAN'],
                ['province_id' => 12, 'area_code' => '12.10', 'name' => 'KAB. LABUHANBATU'],
                ['province_id' => 12, 'area_code' => '12.11', 'name' => 'KAB. DAIRI'],
                ['province_id' => 12, 'area_code' => '12.12', 'name' => 'KAB. TOBA'],
                ['province_id' => 12, 'area_code' => '12.13', 'name' => 'KAB. MANDAILING NATAL'],
                ['province_id' => 12, 'area_code' => '12.14', 'name' => 'KAB. NIAS SELATAN'],
                ['province_id' => 12, 'area_code' => '12.15', 'name' => 'KAB. PAKPAK BHARAT'],
                ['province_id' => 12, 'area_code' => '12.16', 'name' => 'KAB. HUMBANG HASUNDUTAN'],
                ['province_id' => 12, 'area_code' => '12.17', 'name' => 'KAB. SAMOSIR'],
                ['province_id' => 12, 'area_code' => '12.18', 'name' => 'KAB. SERDANG BEDAGAI'],
                ['province_id' => 12, 'area_code' => '12.19', 'name' => 'KAB. BATU BARA'],
                ['province_id' => 12, 'area_code' => '12.20', 'name' => 'KAB. PADANG LAWAS UTARA'],
                ['province_id' => 12, 'area_code' => '12.21', 'name' => 'KAB. PADANG LAWAS'],
                ['province_id' => 12, 'area_code' => '12.22', 'name' => 'KAB. LABUHANBATU SELATAN'],
                ['province_id' => 12, 'area_code' => '12.23', 'name' => 'KAB. LABUHANBATU UTARA'],
                ['province_id' => 12, 'area_code' => '12.24', 'name' => 'KAB. NIAS UTARA'],
                ['province_id' => 12, 'area_code' => '12.25', 'name' => 'KAB. NIAS BARAT'],
                ['province_id' => 12, 'area_code' => '12.71', 'name' => 'KOTA MEDAN'],
                ['province_id' => 12, 'area_code' => '12.72', 'name' => 'KOTA PEMATANGSIANTAR'],
                ['province_id' => 12, 'area_code' => '12.73', 'name' => 'KOTA SIBOLGA'],
                ['province_id' => 12, 'area_code' => '12.74', 'name' => 'KOTA TANJUNG BALAI'],
                ['province_id' => 12, 'area_code' => '12.75', 'name' => 'KOTA BINJAI'],
                ['province_id' => 12, 'area_code' => '12.76', 'name' => 'KOTA TEBING TINGGI'],
                ['province_id' => 12, 'area_code' => '12.77', 'name' => 'KOTA PADANGSIDIMPUAN'],
                ['province_id' => 12, 'area_code' => '12.78', 'name' => 'KOTA GUNUNGSITOLI'],
                ['province_id' => 13, 'area_code' => '13.01', 'name' => 'KAB. PESISIR SELATAN'],
                ['province_id' => 13, 'area_code' => '13.02', 'name' => 'KAB. SOLOK'],
                ['province_id' => 13, 'area_code' => '13.03', 'name' => 'KAB. SIJUNJUNG'],
                ['province_id' => 13, 'area_code' => '13.04', 'name' => 'KAB. TANAH DATAR'],
                ['province_id' => 13, 'area_code' => '13.05', 'name' => 'KAB. PADANG PARIAMAN'],
                ['province_id' => 13, 'area_code' => '13.06', 'name' => 'KAB. AGAM'],
                ['province_id' => 13, 'area_code' => '13.07', 'name' => 'KAB. LIMA PULUH KOTA'],
                ['province_id' => 13, 'area_code' => '13.08', 'name' => 'KAB. PASAMAN'],
                ['province_id' => 13, 'area_code' => '13.09', 'name' => 'KAB. KEPULAUAN MENTAWAI'],
                ['province_id' => 13, 'area_code' => '13.10', 'name' => 'KAB. DHARMASRAYA'],
                ['province_id' => 13, 'area_code' => '13.11', 'name' => 'KAB. SOLOK SELATAN'],
                ['province_id' => 13, 'area_code' => '13.12', 'name' => 'KAB. PASAMAN BARAT'],
                ['province_id' => 13, 'area_code' => '13.71', 'name' => 'KOTA PADANG'],
                ['province_id' => 13, 'area_code' => '13.72', 'name' => 'KOTA SOLOK'],
                ['province_id' => 13, 'area_code' => '13.73', 'name' => 'KOTA SAWAHLUNTO'],
                ['province_id' => 13, 'area_code' => '13.74', 'name' => 'KOTA PADANG PANJANG'],
                ['province_id' => 13, 'area_code' => '13.75', 'name' => 'KOTA BUKITTINGGI'],
                ['province_id' => 13, 'area_code' => '13.76', 'name' => 'KOTA PAYAKUMBUH'],
                ['province_id' => 13, 'area_code' => '13.77', 'name' => 'KOTA PARIAMAN'],
                ['province_id' => 14, 'area_code' => '14.01', 'name' => 'KAB. KAMPAR'],
                ['province_id' => 14, 'area_code' => '14.02', 'name' => 'KAB. INDRAGIRI HULU'],
                ['province_id' => 14, 'area_code' => '14.03', 'name' => 'KAB. BENGKALIS'],
                ['province_id' => 14, 'area_code' => '14.04', 'name' => 'KAB. INDRAGIRI HILIR'],
                ['province_id' => 14, 'area_code' => '14.05', 'name' => 'KAB. PELALAWAN'],
                ['province_id' => 14, 'area_code' => '14.06', 'name' => 'KAB. ROKAN HULU'],
                ['province_id' => 14, 'area_code' => '14.07', 'name' => 'KAB. ROKAN HILIR'],
                ['province_id' => 14, 'area_code' => '14.08', 'name' => 'KAB. SIAK'],
                ['province_id' => 14, 'area_code' => '14.09', 'name' => 'KAB. KUANTAN SINGINGI'],
                ['province_id' => 14, 'area_code' => '14.10', 'name' => 'KAB. KEPULAUAN MERANTI'],
                ['province_id' => 14, 'area_code' => '14.71', 'name' => 'KOTA PEKANBARU'],
                ['province_id' => 14, 'area_code' => '14.72', 'name' => 'KOTA DUMAI'],
                ['province_id' => 15, 'area_code' => '15.01', 'name' => 'KAB. KERINCI'],
                ['province_id' => 15, 'area_code' => '15.02', 'name' => 'KAB. MERANGIN'],
                ['province_id' => 15, 'area_code' => '15.03', 'name' => 'KAB. SAROLANGUN'],
                ['province_id' => 15, 'area_code' => '15.04', 'name' => 'KAB. BATANGHARI'],
                ['province_id' => 15, 'area_code' => '15.05', 'name' => 'KAB. MUARO JAMBI'],
                ['province_id' => 15, 'area_code' => '15.06', 'name' => 'KAB. TANJUNG JABUNG BARAT'],
                ['province_id' => 15, 'area_code' => '15.07', 'name' => 'KAB. TANJUNG JABUNG TIMUR'],
                ['province_id' => 15, 'area_code' => '15.08', 'name' => 'KAB. BUNGO'],
                ['province_id' => 15, 'area_code' => '15.09', 'name' => 'KAB. TEBO'],
                ['province_id' => 15, 'area_code' => '15.71', 'name' => 'KOTA JAMBI'],
                ['province_id' => 15, 'area_code' => '15.72', 'name' => 'KOTA SUNGAI PENUH'],
                ['province_id' => 16, 'area_code' => '16.01', 'name' => 'KAB. OGAN KOMERING ULU'],
                ['province_id' => 16, 'area_code' => '16.02', 'name' => 'KAB. OGAN KOMERING ILIR'],
                ['province_id' => 16, 'area_code' => '16.03', 'name' => 'KAB. MUARA ENIM'],
                ['province_id' => 16, 'area_code' => '16.04', 'name' => 'KAB. LAHAT'],
                ['province_id' => 16, 'area_code' => '16.05', 'name' => 'KAB. MUSI RAWAS'],
                ['province_id' => 16, 'area_code' => '16.06', 'name' => 'KAB. MUSI BANYUASIN'],
                ['province_id' => 16, 'area_code' => '16.07', 'name' => 'KAB. BANYUASIN'],
                ['province_id' => 16, 'area_code' => '16.08', 'name' => 'KAB. OGAN KOMERING ULU TIMUR'],
                ['province_id' => 16, 'area_code' => '16.09', 'name' => 'KAB. OGAN KOMERING ULU SELATAN'],
                ['province_id' => 16, 'area_code' => '16.10', 'name' => 'KAB. OGAN ILIR'],
                ['province_id' => 16, 'area_code' => '16.11', 'name' => 'KAB. EMPAT LAWANG'],
                ['province_id' => 16, 'area_code' => '16.12', 'name' => 'KAB. PENUKAL ABAB LEMATANG ILIR'],
                ['province_id' => 16, 'area_code' => '16.13', 'name' => 'KAB. MUSI RAWAS UTARA'],
                ['province_id' => 16, 'area_code' => '16.71', 'name' => 'KOTA PALEMBANG'],
                ['province_id' => 16, 'area_code' => '16.72', 'name' => 'KOTA PAGAR ALAM'],
                ['province_id' => 16, 'area_code' => '16.73', 'name' => 'KOTA LUBUK LINGGAU'],
                ['province_id' => 16, 'area_code' => '16.74', 'name' => 'KOTA PRABUMULIH'],
                ['province_id' => 17, 'area_code' => '17.01', 'name' => 'KAB. BENGKULU SELATAN'],
                ['province_id' => 17, 'area_code' => '17.02', 'name' => 'KAB. REJANG LEBONG'],
                ['province_id' => 17, 'area_code' => '17.03', 'name' => 'KAB. BENGKULU UTARA'],
                ['province_id' => 17, 'area_code' => '17.04', 'name' => 'KAB. KAUR'],
                ['province_id' => 17, 'area_code' => '17.05', 'name' => 'KAB. SELUMA'],
                ['province_id' => 17, 'area_code' => '17.06', 'name' => 'KAB. MUKO MUKO'],
                ['province_id' => 17, 'area_code' => '17.07', 'name' => 'KAB. LEBONG'],
                ['province_id' => 17, 'area_code' => '17.08', 'name' => 'KAB. KEPAHIANG'],
                ['province_id' => 17, 'area_code' => '17.09', 'name' => 'KAB. BENGKULU TENGAH'],
                ['province_id' => 17, 'area_code' => '17.71', 'name' => 'KOTA BENGKULU'],
                ['province_id' => 18, 'area_code' => '18.01', 'name' => 'KAB. LAMPUNG SELATAN'],
                ['province_id' => 18, 'area_code' => '18.02', 'name' => 'KAB. LAMPUNG TENGAH'],
                ['province_id' => 18, 'area_code' => '18.03', 'name' => 'KAB. LAMPUNG UTARA'],
                ['province_id' => 18, 'area_code' => '18.04', 'name' => 'KAB. LAMPUNG BARAT'],
                ['province_id' => 18, 'area_code' => '18.05', 'name' => 'KAB. TULANG BAWANG'],
                ['province_id' => 18, 'area_code' => '18.06', 'name' => 'KAB. TANGGAMUS'],
                ['province_id' => 18, 'area_code' => '18.07', 'name' => 'KAB. LAMPUNG TIMUR'],
                ['province_id' => 18, 'area_code' => '18.08', 'name' => 'KAB. WAY KANAN'],
                ['province_id' => 18, 'area_code' => '18.09', 'name' => 'KAB. PESAWARAN'],
                ['province_id' => 18, 'area_code' => '18.10', 'name' => 'KAB. PRINGSEWU'],
                ['province_id' => 18, 'area_code' => '18.11', 'name' => 'KAB. MESUJI'],
                ['province_id' => 18, 'area_code' => '18.12', 'name' => 'KAB. TULANG BAWANG BARAT'],
                ['province_id' => 18, 'area_code' => '18.13', 'name' => 'KAB. PESISIR BARAT'],
                ['province_id' => 18, 'area_code' => '18.71', 'name' => 'KOTA BANDAR LAMPUNG'],
                ['province_id' => 18, 'area_code' => '18.72', 'name' => 'KOTA METRO'],
                ['province_id' => 19, 'area_code' => '19.01', 'name' => 'KAB. BANGKA'],
                ['province_id' => 19, 'area_code' => '19.02', 'name' => 'KAB. BELITUNG'],
                ['province_id' => 19, 'area_code' => '19.03', 'name' => 'KAB. BANGKA SELATAN'],
                ['province_id' => 19, 'area_code' => '19.04', 'name' => 'KAB. BANGKA TENGAH'],
                ['province_id' => 19, 'area_code' => '19.05', 'name' => 'KAB. BANGKA BARAT'],
                ['province_id' => 19, 'area_code' => '19.06', 'name' => 'KAB. BELITUNG TIMUR'],
                ['province_id' => 19, 'area_code' => '19.71', 'name' => 'KOTA PANGKAL PINANG'],
                ['province_id' => 21, 'area_code' => '21.01', 'name' => 'KAB. BINTAN'],
                ['province_id' => 21, 'area_code' => '21.02', 'name' => 'KAB. KARIMUN'],
                ['province_id' => 21, 'area_code' => '21.03', 'name' => 'KAB. NATUNA'],
                ['province_id' => 21, 'area_code' => '21.04', 'name' => 'KAB. LINGGA'],
                ['province_id' => 21, 'area_code' => '21.05', 'name' => 'KAB. KEPULAUAN ANAMBAS'],
                ['province_id' => 21, 'area_code' => '21.71', 'name' => 'KOTA BATAM'],
                ['province_id' => 21, 'area_code' => '21.72', 'name' => 'KOTA TANJUNG PINANG'],
                ['province_id' => 31, 'area_code' => '31.01', 'name' => 'KAB. ADM. KEP. SERIBU'],
                ['province_id' => 31, 'area_code' => '31.71', 'name' => 'KOTA ADM. JAKARTA PUSAT'],
                ['province_id' => 31, 'area_code' => '31.72', 'name' => 'KOTA ADM. JAKARTA UTARA'],
                ['province_id' => 31, 'area_code' => '31.73', 'name' => 'KOTA ADM. JAKARTA BARAT'],
                ['province_id' => 31, 'area_code' => '31.74', 'name' => 'KOTA ADM. JAKARTA SELATAN'],
                ['province_id' => 31, 'area_code' => '31.75', 'name' => 'KOTA ADM. JAKARTA TIMUR'],
                ['province_id' => 32, 'area_code' => '32.01', 'name' => 'KAB. BOGOR'],
                ['province_id' => 32, 'area_code' => '32.02', 'name' => 'KAB. SUKABUMI'],
                ['province_id' => 32, 'area_code' => '32.03', 'name' => 'KAB. CIANJUR'],
                ['province_id' => 32, 'area_code' => '32.04', 'name' => 'KAB. BANDUNG'],
                ['province_id' => 32, 'area_code' => '32.05', 'name' => 'KAB. GARUT'],
                ['province_id' => 32, 'area_code' => '32.06', 'name' => 'KAB. TASIKMALAYA'],
                ['province_id' => 32, 'area_code' => '32.07', 'name' => 'KAB. CIAMIS'],
                ['province_id' => 32, 'area_code' => '32.08', 'name' => 'KAB. KUNINGAN'],
                ['province_id' => 32, 'area_code' => '32.09', 'name' => 'KAB. CIREBON'],
                ['province_id' => 32, 'area_code' => '32.10', 'name' => 'KAB. MAJALENGKA'],
                ['province_id' => 32, 'area_code' => '32.11', 'name' => 'KAB. SUMEDANG'],
                ['province_id' => 32, 'area_code' => '32.12', 'name' => 'KAB. INDRAMAYU'],
                ['province_id' => 32, 'area_code' => '32.13', 'name' => 'KAB. SUBANG'],
                ['province_id' => 32, 'area_code' => '32.14', 'name' => 'KAB. PURWAKARTA'],
                ['province_id' => 32, 'area_code' => '32.15', 'name' => 'KAB. KARAWANG'],
                ['province_id' => 32, 'area_code' => '32.16', 'name' => 'KAB. BEKASI'],
                ['province_id' => 32, 'area_code' => '32.17', 'name' => 'KAB. BANDUNG BARAT'],
                ['province_id' => 32, 'area_code' => '32.18', 'name' => 'KAB. PANGANDARAN'],
                ['province_id' => 32, 'area_code' => '32.71', 'name' => 'KOTA BOGOR'],
                ['province_id' => 32, 'area_code' => '32.72', 'name' => 'KOTA SUKABUMI'],
                ['province_id' => 32, 'area_code' => '32.73', 'name' => 'KOTA BANDUNG'],
                ['province_id' => 32, 'area_code' => '32.74', 'name' => 'KOTA CIREBON'],
                ['province_id' => 32, 'area_code' => '32.75', 'name' => 'KOTA BEKASI'],
                ['province_id' => 32, 'area_code' => '32.76', 'name' => 'KOTA DEPOK'],
                ['province_id' => 32, 'area_code' => '32.77', 'name' => 'KOTA CIMAHI'],
                ['province_id' => 32, 'area_code' => '32.78', 'name' => 'KOTA TASIKMALAYA'],
                ['province_id' => 32, 'area_code' => '32.79', 'name' => 'KOTA BANJAR'],
                ['province_id' => 33, 'area_code' => '33.01', 'name' => 'KAB. CILACAP'],
                ['province_id' => 33, 'area_code' => '33.02', 'name' => 'KAB. BANYUMAS'],
                ['province_id' => 33, 'area_code' => '33.03', 'name' => 'KAB. PURBALINGGA'],
                ['province_id' => 33, 'area_code' => '33.04', 'name' => 'KAB. BANJARNEGARA'],
                ['province_id' => 33, 'area_code' => '33.05', 'name' => 'KAB. KEBUMEN'],
                ['province_id' => 33, 'area_code' => '33.06', 'name' => 'KAB. PURWOREJO'],
                ['province_id' => 33, 'area_code' => '33.07', 'name' => 'KAB. WONOSOBO'],
                ['province_id' => 33, 'area_code' => '33.08', 'name' => 'KAB. MAGELANG'],
                ['province_id' => 33, 'area_code' => '33.09', 'name' => 'KAB. BOYOLALI'],
                ['province_id' => 33, 'area_code' => '33.10', 'name' => 'KAB. KLATEN'],
                ['province_id' => 33, 'area_code' => '33.11', 'name' => 'KAB. SUKOHARJO'],
                ['province_id' => 33, 'area_code' => '33.12', 'name' => 'KAB. WONOGIRI'],
                ['province_id' => 33, 'area_code' => '33.13', 'name' => 'KAB. KARANGANYAR'],
                ['province_id' => 33, 'area_code' => '33.14', 'name' => 'KAB. SRAGEN'],
                ['province_id' => 33, 'area_code' => '33.15', 'name' => 'KAB. GROBOGAN'],
                ['province_id' => 33, 'area_code' => '33.16', 'name' => 'KAB. BLORA'],
                ['province_id' => 33, 'area_code' => '33.17', 'name' => 'KAB. REMBANG'],
                ['province_id' => 33, 'area_code' => '33.18', 'name' => 'KAB. PATI'],
                ['province_id' => 33, 'area_code' => '33.19', 'name' => 'KAB. KUDUS'],
                ['province_id' => 33, 'area_code' => '33.20', 'name' => 'KAB. JEPARA'],
                ['province_id' => 33, 'area_code' => '33.21', 'name' => 'KAB. DEMAK'],
                ['province_id' => 33, 'area_code' => '33.22', 'name' => 'KAB. SEMARANG'],
                ['province_id' => 33, 'area_code' => '33.23', 'name' => 'KAB. TEMANGGUNG'],
                ['province_id' => 33, 'area_code' => '33.24', 'name' => 'KAB. KENDAL'],
                ['province_id' => 33, 'area_code' => '33.25', 'name' => 'KAB. BATANG'],
                ['province_id' => 33, 'area_code' => '33.26', 'name' => 'KAB. PEKALONGAN'],
                ['province_id' => 33, 'area_code' => '33.27', 'name' => 'KAB. PEMALANG'],
                ['province_id' => 33, 'area_code' => '33.28', 'name' => 'KAB. TEGAL'],
                ['province_id' => 33, 'area_code' => '33.29', 'name' => 'KAB. BREBES'],
                ['province_id' => 33, 'area_code' => '33.71', 'name' => 'KOTA MAGELANG'],
                ['province_id' => 33, 'area_code' => '33.72', 'name' => 'KOTA SURAKARTA'],
                ['province_id' => 33, 'area_code' => '33.73', 'name' => 'KOTA SALATIGA'],
                ['province_id' => 33, 'area_code' => '33.74', 'name' => 'KOTA SEMARANG'],
                ['province_id' => 33, 'area_code' => '33.75', 'name' => 'KOTA PEKALONGAN'],
                ['province_id' => 33, 'area_code' => '33.76', 'name' => 'KOTA TEGAL'],
                ['province_id' => 34, 'area_code' => '34.01', 'name' => 'KAB. KULON PROGO'],
                ['province_id' => 34, 'area_code' => '34.02', 'name' => 'KAB. BANTUL'],
                ['province_id' => 34, 'area_code' => '34.03', 'name' => 'KAB. GUNUNGKIDUL'],
                ['province_id' => 34, 'area_code' => '34.04', 'name' => 'KAB. SLEMAN'],
                ['province_id' => 34, 'area_code' => '34.71', 'name' => 'KOTA YOGYAKARTA'],
                ['province_id' => 35, 'area_code' => '35.01', 'name' => 'KAB. PACITAN'],
                ['province_id' => 35, 'area_code' => '35.02', 'name' => 'KAB. PONOROGO'],
                ['province_id' => 35, 'area_code' => '35.03', 'name' => 'KAB. TRENGGALEK'],
                ['province_id' => 35, 'area_code' => '35.04', 'name' => 'KAB. TULUNGAGUNG'],
                ['province_id' => 35, 'area_code' => '35.05', 'name' => 'KAB. BLITAR'],
                ['province_id' => 35, 'area_code' => '35.06', 'name' => 'KAB. KEDIRI'],
                ['province_id' => 35, 'area_code' => '35.07', 'name' => 'KAB. MALANG'],
                ['province_id' => 35, 'area_code' => '35.08', 'name' => 'KAB. LUMAJANG'],
                ['province_id' => 35, 'area_code' => '35.09', 'name' => 'KAB. JEMBER'],
                ['province_id' => 35, 'area_code' => '35.10', 'name' => 'KAB. BANYUWANGI'],
                ['province_id' => 35, 'area_code' => '35.11', 'name' => 'KAB. BONDOWOSO'],
                ['province_id' => 35, 'area_code' => '35.12', 'name' => 'KAB. SITUBONDO'],
                ['province_id' => 35, 'area_code' => '35.13', 'name' => 'KAB. PROBOLINGGO'],
                ['province_id' => 35, 'area_code' => '35.14', 'name' => 'KAB. PASURUAN'],
                ['province_id' => 35, 'area_code' => '35.15', 'name' => 'KAB. SIDOARJO'],
                ['province_id' => 35, 'area_code' => '35.16', 'name' => 'KAB. MOJOKERTO'],
                ['province_id' => 35, 'area_code' => '35.17', 'name' => 'KAB. JOMBANG'],
                ['province_id' => 35, 'area_code' => '35.18', 'name' => 'KAB. NGANJUK'],
                ['province_id' => 35, 'area_code' => '35.19', 'name' => 'KAB. MADIUN'],
                ['province_id' => 35, 'area_code' => '35.20', 'name' => 'KAB. MAGETAN'],
                ['province_id' => 35, 'area_code' => '35.21', 'name' => 'KAB. NGAWI'],
                ['province_id' => 35, 'area_code' => '35.22', 'name' => 'KAB. BOJONEGORO'],
                ['province_id' => 35, 'area_code' => '35.23', 'name' => 'KAB. TUBAN'],
                ['province_id' => 35, 'area_code' => '35.24', 'name' => 'KAB. LAMONGAN'],
                ['province_id' => 35, 'area_code' => '35.25', 'name' => 'KAB. GRESIK'],
                ['province_id' => 35, 'area_code' => '35.26', 'name' => 'KAB. BANGKALAN'],
                ['province_id' => 35, 'area_code' => '35.27', 'name' => 'KAB. SAMPANG'],
                ['province_id' => 35, 'area_code' => '35.28', 'name' => 'KAB. PAMEKASAN'],
                ['province_id' => 35, 'area_code' => '35.29', 'name' => 'KAB. SUMENEP'],
                ['province_id' => 35, 'area_code' => '35.71', 'name' => 'KOTA KEDIRI'],
                ['province_id' => 35, 'area_code' => '35.72', 'name' => 'KOTA BLITAR'],
                ['province_id' => 35, 'area_code' => '35.73', 'name' => 'KOTA MALANG'],
                ['province_id' => 35, 'area_code' => '35.74', 'name' => 'KOTA PROBOLINGGO'],
                ['province_id' => 35, 'area_code' => '35.75', 'name' => 'KOTA PASURUAN'],
                ['province_id' => 35, 'area_code' => '35.76', 'name' => 'KOTA MOJOKERTO'],
                ['province_id' => 35, 'area_code' => '35.77', 'name' => 'KOTA MADIUN'],
                ['province_id' => 35, 'area_code' => '35.78', 'name' => 'KOTA SURABAYA'],
                ['province_id' => 35, 'area_code' => '35.79', 'name' => 'KOTA BATU'],
                ['province_id' => 36, 'area_code' => '36.01', 'name' => 'KAB. PANDEGLANG'],
                ['province_id' => 36, 'area_code' => '36.02', 'name' => 'KAB. LEBAK'],
                ['province_id' => 36, 'area_code' => '36.03', 'name' => 'KAB. TANGERANG'],
                ['province_id' => 36, 'area_code' => '36.04', 'name' => 'KAB. SERANG'],
                ['province_id' => 36, 'area_code' => '36.71', 'name' => 'KOTA TANGERANG'],
                ['province_id' => 36, 'area_code' => '36.72', 'name' => 'KOTA CILEGON'],
                ['province_id' => 36, 'area_code' => '36.73', 'name' => 'KOTA SERANG'],
                ['province_id' => 36, 'area_code' => '36.74', 'name' => 'KOTA TANGERANG SELATAN'],
                ['province_id' => 51, 'area_code' => '51.01', 'name' => 'KAB. JEMBRANA'],
                ['province_id' => 51, 'area_code' => '51.02', 'name' => 'KAB. TABANAN'],
                ['province_id' => 51, 'area_code' => '51.03', 'name' => 'KAB. BADUNG'],
                ['province_id' => 51, 'area_code' => '51.04', 'name' => 'KAB. GIANYAR'],
                ['province_id' => 51, 'area_code' => '51.05', 'name' => 'KAB. KLUNGKUNG'],
                ['province_id' => 51, 'area_code' => '51.06', 'name' => 'KAB. BANGLI'],
                ['province_id' => 51, 'area_code' => '51.07', 'name' => 'KAB. KARANGASEM'],
                ['province_id' => 51, 'area_code' => '51.08', 'name' => 'KAB. BULELENG'],
                ['province_id' => 51, 'area_code' => '51.71', 'name' => 'KOTA DENPASAR'],
                ['province_id' => 52, 'area_code' => '52.01', 'name' => 'KAB. LOMBOK BARAT'],
                ['province_id' => 52, 'area_code' => '52.02', 'name' => 'KAB. LOMBOK TENGAH'],
                ['province_id' => 52, 'area_code' => '52.03', 'name' => 'KAB. LOMBOK TIMUR'],
                ['province_id' => 52, 'area_code' => '52.04', 'name' => 'KAB. SUMBAWA'],
                ['province_id' => 52, 'area_code' => '52.05', 'name' => 'KAB. DOMPU'],
                ['province_id' => 52, 'area_code' => '52.06', 'name' => 'KAB. BIMA'],
                ['province_id' => 52, 'area_code' => '52.07', 'name' => 'KAB. SUMBAWA BARAT'],
                ['province_id' => 52, 'area_code' => '52.08', 'name' => 'KAB. LOMBOK UTARA'],
                ['province_id' => 52, 'area_code' => '52.71', 'name' => 'KOTA MATARAM'],
                ['province_id' => 52, 'area_code' => '52.72', 'name' => 'KOTA BIMA'],
                ['province_id' => 53, 'area_code' => '53.01', 'name' => 'KAB. KUPANG'],
                ['province_id' => 53, 'area_code' => '53.02', 'name' => 'KAB TIMOR TENGAH SELATAN'],
                ['province_id' => 53, 'area_code' => '53.03', 'name' => 'KAB. TIMOR TENGAH UTARA'],
                ['province_id' => 53, 'area_code' => '53.04', 'name' => 'KAB. BELU'],
                ['province_id' => 53, 'area_code' => '53.05', 'name' => 'KAB. ALOR'],
                ['province_id' => 53, 'area_code' => '53.06', 'name' => 'KAB. FLORES TIMUR'],
                ['province_id' => 53, 'area_code' => '53.07', 'name' => 'KAB. SIKKA'],
                ['province_id' => 53, 'area_code' => '53.08', 'name' => 'KAB. ENDE'],
                ['province_id' => 53, 'area_code' => '53.09', 'name' => 'KAB. NGADA'],
                ['province_id' => 53, 'area_code' => '53.10', 'name' => 'KAB. MANGGARAI'],
                ['province_id' => 53, 'area_code' => '53.11', 'name' => 'KAB. SUMBA TIMUR'],
                ['province_id' => 53, 'area_code' => '53.12', 'name' => 'KAB. SUMBA BARAT'],
                ['province_id' => 53, 'area_code' => '53.13', 'name' => 'KAB. LEMBATA'],
                ['province_id' => 53, 'area_code' => '53.14', 'name' => 'KAB. ROTE NDAO'],
                ['province_id' => 53, 'area_code' => '53.15', 'name' => 'KAB. MANGGARAI BARAT'],
                ['province_id' => 53, 'area_code' => '53.16', 'name' => 'KAB. NAGEKEO'],
                ['province_id' => 53, 'area_code' => '53.17', 'name' => 'KAB. SUMBA TENGAH'],
                ['province_id' => 53, 'area_code' => '53.18', 'name' => 'KAB. SUMBA BARAT DAYA'],
                ['province_id' => 53, 'area_code' => '53.19', 'name' => 'KAB. MANGGARAI TIMUR'],
                ['province_id' => 53, 'area_code' => '53.20', 'name' => 'KAB. SABU RAIJUA'],
                ['province_id' => 53, 'area_code' => '53.21', 'name' => 'KAB. MALAKA'],
                ['province_id' => 53, 'area_code' => '53.71', 'name' => 'KOTA KUPANG'],
                ['province_id' => 61, 'area_code' => '61.01', 'name' => 'KAB. SAMBAS'],
                ['province_id' => 61, 'area_code' => '61.02', 'name' => 'KAB. MEMPAWAH'],
                ['province_id' => 61, 'area_code' => '61.03', 'name' => 'KAB. SANGGAU'],
                ['province_id' => 61, 'area_code' => '61.04', 'name' => 'KAB. KETAPANG'],
                ['province_id' => 61, 'area_code' => '61.05', 'name' => 'KAB. SINTANG'],
                ['province_id' => 61, 'area_code' => '61.06', 'name' => 'KAB. KAPUAS HULU'],
                ['province_id' => 61, 'area_code' => '61.07', 'name' => 'KAB. BENGKAYANG'],
                ['province_id' => 61, 'area_code' => '61.08', 'name' => 'KAB. LANDAK'],
                ['province_id' => 61, 'area_code' => '61.09', 'name' => 'KAB. SEKADAU'],
                ['province_id' => 61, 'area_code' => '61.10', 'name' => 'KAB. MELAWI'],
                ['province_id' => 61, 'area_code' => '61.11', 'name' => 'KAB. KAYONG UTARA'],
                ['province_id' => 61, 'area_code' => '61.12', 'name' => 'KAB. KUBU RAYA'],
                ['province_id' => 61, 'area_code' => '61.71', 'name' => 'KOTA PONTIANAK'],
                ['province_id' => 61, 'area_code' => '61.72', 'name' => 'KOTA SINGKAWANG'],
                ['province_id' => 62, 'area_code' => '62.01', 'name' => 'KAB. KOTAWARINGIN BARAT'],
                ['province_id' => 62, 'area_code' => '62.02', 'name' => 'KAB. KOTAWARINGIN TIMUR'],
                ['province_id' => 62, 'area_code' => '62.03', 'name' => 'KAB. KAPUAS'],
                ['province_id' => 62, 'area_code' => '62.04', 'name' => 'KAB. BARITO SELATAN'],
                ['province_id' => 62, 'area_code' => '62.05', 'name' => 'KAB. BARITO UTARA'],
                ['province_id' => 62, 'area_code' => '62.06', 'name' => 'KAB. KATINGAN'],
                ['province_id' => 62, 'area_code' => '62.07', 'name' => 'KAB. SERUYAN'],
                ['province_id' => 62, 'area_code' => '62.08', 'name' => 'KAB. SUKAMARA'],
                ['province_id' => 62, 'area_code' => '62.09', 'name' => 'KAB. LAMANDAU'],
                ['province_id' => 62, 'area_code' => '62.10', 'name' => 'KAB. GUNUNG MAS'],
                ['province_id' => 62, 'area_code' => '62.11', 'name' => 'KAB. PULANG PISAU'],
                ['province_id' => 62, 'area_code' => '62.12', 'name' => 'KAB. MURUNG RAYA'],
                ['province_id' => 62, 'area_code' => '62.13', 'name' => 'KAB. BARITO TIMUR'],
                ['province_id' => 62, 'area_code' => '62.71', 'name' => 'KOTA PALANGKARAYA'],
                ['province_id' => 63, 'area_code' => '63.01', 'name' => 'KAB. TANAH LAUT'],
                ['province_id' => 63, 'area_code' => '63.02', 'name' => 'KAB. KOTABARU'],
                ['province_id' => 63, 'area_code' => '63.03', 'name' => 'KAB. BANJAR'],
                ['province_id' => 63, 'area_code' => '63.04', 'name' => 'KAB. BARITO KUALA'],
                ['province_id' => 63, 'area_code' => '63.05', 'name' => 'KAB. TAPIN'],
                ['province_id' => 63, 'area_code' => '63.06', 'name' => 'KAB. HULU SUNGAI SELATAN'],
                ['province_id' => 63, 'area_code' => '63.07', 'name' => 'KAB. HULU SUNGAI TENGAH'],
                ['province_id' => 63, 'area_code' => '63.08', 'name' => 'KAB. HULU SUNGAI UTARA'],
                ['province_id' => 63, 'area_code' => '63.09', 'name' => 'KAB. TABALONG'],
                ['province_id' => 63, 'area_code' => '63.10', 'name' => 'KAB. TANAH BUMBU'],
                ['province_id' => 63, 'area_code' => '63.11', 'name' => 'KAB. BALANGAN'],
                ['province_id' => 63, 'area_code' => '63.71', 'name' => 'KOTA BANJARMASIN'],
                ['province_id' => 63, 'area_code' => '63.72', 'name' => 'KOTA BANJARBARU'],
                ['province_id' => 64, 'area_code' => '64.01', 'name' => 'KAB. PASER'],
                ['province_id' => 64, 'area_code' => '64.02', 'name' => 'KAB. KUTAI KARTANEGARA'],
                ['province_id' => 64, 'area_code' => '64.03', 'name' => 'KAB. BERAU'],
                ['province_id' => 64, 'area_code' => '64.07', 'name' => 'KAB. KUTAI BARAT'],
                ['province_id' => 64, 'area_code' => '64.08', 'name' => 'KAB. KUTAI TIMUR'],
                ['province_id' => 64, 'area_code' => '64.09', 'name' => 'KAB. PENAJAM PASER UTARA'],
                ['province_id' => 64, 'area_code' => '64.11', 'name' => 'KAB. MAHAKAM ULU'],
                ['province_id' => 64, 'area_code' => '64.71', 'name' => 'KOTA BALIKPAPAN'],
                ['province_id' => 64, 'area_code' => '64.72', 'name' => 'KOTA SAMARINDA'],
                ['province_id' => 64, 'area_code' => '64.74', 'name' => 'KOTA BONTANG'],
                ['province_id' => 65, 'area_code' => '65.01', 'name' => 'KAB. BULUNGAN'],
                ['province_id' => 65, 'area_code' => '65.02', 'name' => 'KAB. MALINAU'],
                ['province_id' => 65, 'area_code' => '65.03', 'name' => 'KAB. NUNUKAN'],
                ['province_id' => 65, 'area_code' => '65.04', 'name' => 'KAB. TANA TIDUNG'],
                ['province_id' => 65, 'area_code' => '65.71', 'name' => 'KOTA TARAKAN'],
                ['province_id' => 71, 'area_code' => '71.01', 'name' => 'KAB. BOLAANG MONGONDOW'],
                ['province_id' => 71, 'area_code' => '71.02', 'name' => 'KAB. MINAHASA'],
                ['province_id' => 71, 'area_code' => '71.03', 'name' => 'KAB. KEPULAUAN SANGIHE'],
                ['province_id' => 71, 'area_code' => '71.04', 'name' => 'KAB. KEPULAUAN TALAUD'],
                ['province_id' => 71, 'area_code' => '71.05', 'name' => 'KAB. MINAHASA SELATAN'],
                ['province_id' => 71, 'area_code' => '71.06', 'name' => 'KAB. MINAHASA UTARA'],
                ['province_id' => 71, 'area_code' => '71.07', 'name' => 'KAB. MINAHASA TENGGARA'],
                ['province_id' => 71, 'area_code' => '71.08', 'name' => 'KAB. BOLAANG MONGONDOW UTARA'],
                ['province_id' => 71, 'area_code' => '71.09', 'name' => 'KAB. KEP. SIAU TAGULANDANG BIARO'],
                ['province_id' => 71, 'area_code' => '71.10', 'name' => 'KAB. BOLAANG MONGONDOW TIMUR'],
                ['province_id' => 71, 'area_code' => '71.11', 'name' => 'KAB. BOLAANG MONGONDOW SELATAN'],
                ['province_id' => 71, 'area_code' => '71.71', 'name' => 'KOTA MANADO'],
                ['province_id' => 71, 'area_code' => '71.72', 'name' => 'KOTA BITUNG'],
                ['province_id' => 71, 'area_code' => '71.73', 'name' => 'KOTA TOMOHON'],
                ['province_id' => 71, 'area_code' => '71.74', 'name' => 'KOTA KOTAMOBAGU'],
                ['province_id' => 72, 'area_code' => '72.01', 'name' => 'KAB. BANGGAI'],
                ['province_id' => 72, 'area_code' => '72.02', 'name' => 'KAB. POSO'],
                ['province_id' => 72, 'area_code' => '72.03', 'name' => 'KAB. DONGGALA'],
                ['province_id' => 72, 'area_code' => '72.04', 'name' => 'KAB. TOLI TOLI'],
                ['province_id' => 72, 'area_code' => '72.05', 'name' => 'KAB. BUOL'],
                ['province_id' => 72, 'area_code' => '72.06', 'name' => 'KAB. MOROWALI'],
                ['province_id' => 72, 'area_code' => '72.07', 'name' => 'KAB. BANGGAI KEPULAUAN'],
                ['province_id' => 72, 'area_code' => '72.08', 'name' => 'KAB. PARIGI MOUTONG'],
                ['province_id' => 72, 'area_code' => '72.09', 'name' => 'KAB. TOJO UNA UNA'],
                ['province_id' => 72, 'area_code' => '72.10', 'name' => 'KAB. SIGI'],
                ['province_id' => 72, 'area_code' => '72.11', 'name' => 'KAB. BANGGAI LAUT'],
                ['province_id' => 72, 'area_code' => '72.12', 'name' => 'KAB. MOROWALI UTARA'],
                ['province_id' => 72, 'area_code' => '72.71', 'name' => 'KOTA PALU'],
                ['province_id' => 73, 'area_code' => '73.01', 'name' => 'KAB. KEPULAUAN SELAYAR'],
                ['province_id' => 73, 'area_code' => '73.02', 'name' => 'KAB. BULUKUMBA'],
                ['province_id' => 73, 'area_code' => '73.03', 'name' => 'KAB. BANTAENG'],
                ['province_id' => 73, 'area_code' => '73.04', 'name' => 'KAB. JENEPONTO'],
                ['province_id' => 73, 'area_code' => '73.05', 'name' => 'KAB. TAKALAR'],
                ['province_id' => 73, 'area_code' => '73.06', 'name' => 'KAB. GOWA'],
                ['province_id' => 73, 'area_code' => '73.07', 'name' => 'KAB. SINJAI'],
                ['province_id' => 73, 'area_code' => '73.08', 'name' => 'KAB. BONE'],
                ['province_id' => 73, 'area_code' => '73.09', 'name' => 'KAB. MAROS'],
                ['province_id' => 73, 'area_code' => '73.10', 'name' => 'KAB. PANGKAJENE KEPULAUAN'],
                ['province_id' => 73, 'area_code' => '73.11', 'name' => 'KAB. BARRU'],
                ['province_id' => 73, 'area_code' => '73.12', 'name' => 'KAB. SOPPENG'],
                ['province_id' => 73, 'area_code' => '73.13', 'name' => 'KAB. WAJO'],
                ['province_id' => 73, 'area_code' => '73.14', 'name' => 'KAB. SIDENRENG RAPPANG'],
                ['province_id' => 73, 'area_code' => '73.15', 'name' => 'KAB. PINRANG'],
                ['province_id' => 73, 'area_code' => '73.16', 'name' => 'KAB. ENREKANG'],
                ['province_id' => 73, 'area_code' => '73.17', 'name' => 'KAB. LUWU'],
                ['province_id' => 73, 'area_code' => '73.18', 'name' => 'KAB. TANA TORAJA'],
                ['province_id' => 73, 'area_code' => '73.22', 'name' => 'KAB. LUWU UTARA'],
                ['province_id' => 73, 'area_code' => '73.24', 'name' => 'KAB. LUWU TIMUR'],
                ['province_id' => 73, 'area_code' => '73.26', 'name' => 'KAB. TORAJA UTARA'],
                ['province_id' => 73, 'area_code' => '73.71', 'name' => 'KOTA MAKASSAR'],
                ['province_id' => 73, 'area_code' => '73.72', 'name' => 'KOTA PARE PARE'],
                ['province_id' => 73, 'area_code' => '73.73', 'name' => 'KOTA PALOPO'],
                ['province_id' => 74, 'area_code' => '74.01', 'name' => 'KAB. KOLAKA'],
                ['province_id' => 74, 'area_code' => '74.02', 'name' => 'KAB. KONAWE'],
                ['province_id' => 74, 'area_code' => '74.03', 'name' => 'KAB. MUNA'],
                ['province_id' => 74, 'area_code' => '74.04', 'name' => 'KAB. BUTON'],
                ['province_id' => 74, 'area_code' => '74.05', 'name' => 'KAB. KONAWE SELATAN'],
                ['province_id' => 74, 'area_code' => '74.06', 'name' => 'KAB. BOMBANA'],
                ['province_id' => 74, 'area_code' => '74.07', 'name' => 'KAB. WAKATOBI'],
                ['province_id' => 74, 'area_code' => '74.08', 'name' => 'KAB. KOLAKA UTARA'],
                ['province_id' => 74, 'area_code' => '74.09', 'name' => 'KAB. KONAWE UTARA'],
                ['province_id' => 74, 'area_code' => '74.10', 'name' => 'KAB. BUTON UTARA'],
                ['province_id' => 74, 'area_code' => '74.11', 'name' => 'KAB. KOLAKA TIMUR'],
                ['province_id' => 74, 'area_code' => '74.12', 'name' => 'KAB. KONAWE KEPULAUAN'],
                ['province_id' => 74, 'area_code' => '74.13', 'name' => 'KAB. MUNA BARAT'],
                ['province_id' => 74, 'area_code' => '74.14', 'name' => 'KAB. BUTON TENGAH'],
                ['province_id' => 74, 'area_code' => '74.15', 'name' => 'KAB. BUTON SELATAN'],
                ['province_id' => 74, 'area_code' => '74.71', 'name' => 'KOTA KENDARI'],
                ['province_id' => 74, 'area_code' => '74.72', 'name' => 'KOTA BAU BAU'],
                ['province_id' => 75, 'area_code' => '75.01', 'name' => 'KAB. GORONTALO'],
                ['province_id' => 75, 'area_code' => '75.02', 'name' => 'KAB. BOALEMO'],
                ['province_id' => 75, 'area_code' => '75.03', 'name' => 'KAB. BONE BOLANGO'],
                ['province_id' => 75, 'area_code' => '75.04', 'name' => 'KAB. PAHUWATO'],
                ['province_id' => 75, 'area_code' => '75.05', 'name' => 'KAB. GORONTALO UTARA'],
                ['province_id' => 75, 'area_code' => '75.71', 'name' => 'KOTA GORONTALO'],
                ['province_id' => 76, 'area_code' => '76.01', 'name' => 'KAB. PASANGKAYU'],
                ['province_id' => 76, 'area_code' => '76.02', 'name' => 'KAB. MAMUJU'],
                ['province_id' => 76, 'area_code' => '76.03', 'name' => 'KAB. MAMASA'],
                ['province_id' => 76, 'area_code' => '76.04', 'name' => 'KAB. POLEWALI MANDAR'],
                ['province_id' => 76, 'area_code' => '76.05', 'name' => 'KAB. MAJENE'],
                ['province_id' => 76, 'area_code' => '76.06', 'name' => 'KAB. MAMUJU TENGAH'],
                ['province_id' => 81, 'area_code' => '81.01', 'name' => 'KAB. MALUKU TENGAH'],
                ['province_id' => 81, 'area_code' => '81.02', 'name' => 'KAB. MALUKU TENGGARA'],
                ['province_id' => 81, 'area_code' => '81.03', 'name' => 'KAB. KEPULAUAN TANIMBAR'],
                ['province_id' => 81, 'area_code' => '81.04', 'name' => 'KAB. BURU'],
                ['province_id' => 81, 'area_code' => '81.05', 'name' => 'KAB. SERAM BAGIAN TIMUR'],
                ['province_id' => 81, 'area_code' => '81.06', 'name' => 'KAB. SERAM BAGIAN BARAT'],
                ['province_id' => 81, 'area_code' => '81.07', 'name' => 'KAB. KEPULAUAN ARU'],
                ['province_id' => 81, 'area_code' => '81.08', 'name' => 'KAB. MALUKU BARAT DAYA'],
                ['province_id' => 81, 'area_code' => '81.09', 'name' => 'KAB. BURU SELATAN'],
                ['province_id' => 81, 'area_code' => '81.71', 'name' => 'KOTA AMBON'],
                ['province_id' => 81, 'area_code' => '81.72', 'name' => 'KOTA TUAL'],
                ['province_id' => 82, 'area_code' => '82.01', 'name' => 'KAB. HALMAHERA BARAT'],
                ['province_id' => 82, 'area_code' => '82.02', 'name' => 'KAB. HALMAHERA TENGAH'],
                ['province_id' => 82, 'area_code' => '82.03', 'name' => 'KAB. HALMAHERA UTARA'],
                ['province_id' => 82, 'area_code' => '82.04', 'name' => 'KAB. HALMAHERA SELATAN'],
                ['province_id' => 82, 'area_code' => '82.05', 'name' => 'KAB. KEPULAUAN SULA'],
                ['province_id' => 82, 'area_code' => '82.06', 'name' => 'KAB. HALMAHERA TIMUR'],
                ['province_id' => 82, 'area_code' => '82.07', 'name' => 'KAB. PULAU MOROTAI'],
                ['province_id' => 82, 'area_code' => '82.08', 'name' => 'KAB. PULAU TALIABU'],
                ['province_id' => 82, 'area_code' => '82.71', 'name' => 'KOTA TERNATE'],
                ['province_id' => 82, 'area_code' => '82.72', 'name' => 'KOTA TIDORE KEPULAUAN'],
                ['province_id' => 91, 'area_code' => '91.01', 'name' => 'KAB. MERAUKE'],
                ['province_id' => 91, 'area_code' => '91.02', 'name' => 'KAB. JAYAWIJAYA'],
                ['province_id' => 91, 'area_code' => '91.03', 'name' => 'KAB. JAYAPURA'],
                ['province_id' => 91, 'area_code' => '91.04', 'name' => 'KAB. NABIRE'],
                ['province_id' => 91, 'area_code' => '91.05', 'name' => 'KAB. KEPULAUAN YAPEN'],
                ['province_id' => 91, 'area_code' => '91.06', 'name' => 'KAB. BIAK NUMFOR'],
                ['province_id' => 91, 'area_code' => '91.07', 'name' => 'KAB. PUNCAK JAYA'],
                ['province_id' => 91, 'area_code' => '91.08', 'name' => 'KAB. PANIAI'],
                ['province_id' => 91, 'area_code' => '91.09', 'name' => 'KAB. MIMIKA'],
                ['province_id' => 91, 'area_code' => '91.10', 'name' => 'KAB. SARMI'],
                ['province_id' => 91, 'area_code' => '91.11', 'name' => 'KAB. KEEROM'],
                ['province_id' => 91, 'area_code' => '91.12', 'name' => 'KAB. PEGUNUNGAN BINTANG'],
                ['province_id' => 91, 'area_code' => '91.13', 'name' => 'KAB. YAHUKIMO'],
                ['province_id' => 91, 'area_code' => '91.14', 'name' => 'KAB. TOLIKARA'],
                ['province_id' => 91, 'area_code' => '91.15', 'name' => 'KAB. WAROPEN'],
                ['province_id' => 91, 'area_code' => '91.16', 'name' => 'KAB. BOVEN DIGOEL'],
                ['province_id' => 91, 'area_code' => '91.17', 'name' => 'KAB. MAPPI'],
                ['province_id' => 91, 'area_code' => '91.18', 'name' => 'KAB. ASMAT'],
                ['province_id' => 91, 'area_code' => '91.19', 'name' => 'KAB. SUPIORI'],
                ['province_id' => 91, 'area_code' => '91.20', 'name' => 'KAB. MAMBERAMO RAYA'],
                ['province_id' => 91, 'area_code' => '91.21', 'name' => 'KAB. MAMBERAMO TENGAH'],
                ['province_id' => 91, 'area_code' => '91.22', 'name' => 'KAB. YALIMO'],
                ['province_id' => 91, 'area_code' => '91.23', 'name' => 'KAB. LANNY JAYA'],
                ['province_id' => 91, 'area_code' => '91.24', 'name' => 'KAB. NDUGA'],
                ['province_id' => 91, 'area_code' => '91.25', 'name' => 'KAB. PUNCAK'],
                ['province_id' => 91, 'area_code' => '91.26', 'name' => 'KAB. DOGIYAI'],
                ['province_id' => 91, 'area_code' => '91.27', 'name' => 'KAB. INTAN JAYA'],
                ['province_id' => 91, 'area_code' => '91.28', 'name' => 'KAB. DEIYAI'],
                ['province_id' => 91, 'area_code' => '91.71', 'name' => 'KOTA JAYAPURA'],
                ['province_id' => 92, 'area_code' => '92.01', 'name' => 'KAB. SORONG'],
                ['province_id' => 92, 'area_code' => '92.02', 'name' => 'KAB. MANOKWARI'],
                ['province_id' => 92, 'area_code' => '92.03', 'name' => 'KAB. FAK FAK'],
                ['province_id' => 92, 'area_code' => '92.04', 'name' => 'KAB. SORONG SELATAN'],
                ['province_id' => 92, 'area_code' => '92.05', 'name' => 'KAB. RAJA AMPAT'],
                ['province_id' => 92, 'area_code' => '92.06', 'name' => 'KAB. TELUK BINTUNI'],
                ['province_id' => 92, 'area_code' => '92.07', 'name' => 'KAB. TELUK WONDAMA'],
                ['province_id' => 92, 'area_code' => '92.08', 'name' => 'KAB. KAIMANA'],
                ['province_id' => 92, 'area_code' => '92.09', 'name' => 'KAB. TAMBRAUW'],
                ['province_id' => 92, 'area_code' => '92.10', 'name' => 'KAB. MAYBRAT'],
                ['province_id' => 92, 'area_code' => '92.11', 'name' => 'KAB. MANOKWARI SELATAN'],
                ['province_id' => 92, 'area_code' => '92.12', 'name' => 'KAB. PEGUNUNGAN ARFAK'],
                ['province_id' => 92, 'area_code' => '92.71', 'name' => 'KOTA SORONG']
            ];
        }
    }
